apiVersion: v1
kind: Service
metadata:
  name: anchore-engine-service
  labels:
    app: anchore-engine-core
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8228
      protocol: TCP
      name: external-api
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: simplequeue
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: catalog
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: policyengine
    - port: 8338
      targetPort: 8338
      protocol: TCP
      name: k8swebhook
  selector:
    app: anchore-engine-core

