apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: anchore-engine-core-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anchore-engine-core
    spec:
      containers:
        - name: anchore-engine
          image: anchore/anchore-engine:latest
          ports:
            - containerPort: 8228
              name: external-api
            - containerPort: 8083
              name: queue-service
          env:
          - name: ANCHORE_HOST_ID
            value: 'anchore_core_service'
          - name: ANCHORE_DB_USER
            value: postgres
          - name: ANCHORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anchore-db-postgresql
                key: postgres-password
          - name: ANCHORE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anchore-engine-user-creds
                key: admin_password
          volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: anchore-core-config
