apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: anchore-engine-analyzer-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anchore-engine-analyzer
    spec:
      containers:
        - name: anchore-engine
          image: anchore/anchore-engine:latest
          ports:
            - containerPort: 8082
              name: analyzer-api
          env:
          - name: ANCHORE_DB_USER
            value: postgres
          - name: ANCHORE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anchore-db-postgresql
                key: postgres-password
          - name: ANCHORE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anchore-engine-user-creds
                key: admin_password
          volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
        - name: config-volume
          configMap:
            name: anchore-worker-config
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock


