apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: anchore-engine-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: anchore-engine
    servicePort: 80
  tls:
  - secretName: tlstestsecret

